//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLVS.Dal.Company
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADM2
    {
        public int Code { get; set; }
        public string TaxAuCod { get; set; }
        public string KeyEcoAct { get; set; }
        public string TaxPayType { get; set; }
        public string TaxLegForm { get; set; }
        public string RegName { get; set; }
        public string RegNameExt { get; set; }
        public string SoleFName { get; set; }
        public string SoleSName { get; set; }
        public string SoleTitle { get; set; }
        public string CityTown { get; set; }
        public string ZipCode { get; set; }
        public string Telephone { get; set; }
        public string Street { get; set; }
        public string StreetNum { get; set; }
        public Nullable<int> BuildinNum { get; set; }
        public string Email { get; set; }
        public string State { get; set; }
        public string RepType { get; set; }
        public string RepCode { get; set; }
        public string RepFName { get; set; }
        public string RepSName { get; set; }
        public string CompName { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string TaxACNum { get; set; }
        public string LegEntitID { get; set; }
        public string AuthFName { get; set; }
        public string AuthLName { get; set; }
        public string AuthRelat { get; set; }
        public string AuthType { get; set; }
        public string TaxPayAttr { get; set; }
        public string Classifier { get; set; }
        public string DeprMethod { get; set; }
        public string SubmitPlac { get; set; }
        public string BgtClass { get; set; }
        public string SubjOfRuF { get; set; }
        public string AuthFathrN { get; set; }
    }
}
