//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLVS.Dal.Company
{
    using System;
    using System.Collections.Generic;
    
    public partial class AFA1
    {
        public int DocEntry { get; set; }
        public int LineNum { get; set; }
        public string ItemCode { get; set; }
        public string AcctCode { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> LineTotal { get; set; }
        public Nullable<decimal> TotalFrgn { get; set; }
        public Nullable<decimal> TotalSys { get; set; }
        public string DprArea { get; set; }
        public string Remarks { get; set; }
        public int LogInstanc { get; set; }
        public string NewItemCod { get; set; }
        public string Partial { get; set; }
        public Nullable<decimal> APC { get; set; }
        public string NewAstCls { get; set; }
        public string ObjType { get; set; }
        public string TransType { get; set; }
    }
}
