//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLVS.Dal.Company
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARC1
    {
        public int DocNum { get; set; }
        public int LineID { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<int> CheckNum { get; set; }
        public string BankCode { get; set; }
        public string Branch { get; set; }
        public string AcctNum { get; set; }
        public string Details { get; set; }
        public string Trnsfrable { get; set; }
        public Nullable<decimal> CheckSum { get; set; }
        public string Currency { get; set; }
        public Nullable<int> Flags { get; set; }
        public string ObjType { get; set; }
        public int LogInstanc { get; set; }
        public string CountryCod { get; set; }
        public string CheckAct { get; set; }
        public Nullable<int> CheckAbs { get; set; }
        public Nullable<int> BnkActKey { get; set; }
        public string ManualChk { get; set; }
    }
}
