//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLVS.Dal.Company
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRD1
    {
        public string Address { get; set; }
        public string CardCode { get; set; }
        public string Street { get; set; }
        public string Block { get; set; }
        public string ZipCode { get; set; }
        public string City { get; set; }
        public string County { get; set; }
        public string Country { get; set; }
        public string State { get; set; }
        public Nullable<short> UserSign { get; set; }
        public Nullable<int> LogInstanc { get; set; }
        public string ObjType { get; set; }
        public string LicTradNum { get; set; }
        public Nullable<int> LineNum { get; set; }
        public string TaxCode { get; set; }
        public string Building { get; set; }
        public string AdresType { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public string AddrType { get; set; }
        public string StreetNo { get; set; }
        public string AltCrdName { get; set; }
        public string AltTaxId { get; set; }
        public string TaxOffice { get; set; }
        public string GlblLocNum { get; set; }
    }
}
