//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLVS.Dal.Company
{
    using System;
    using System.Collections.Generic;
    
    public partial class ECM2
    {
        public int AbsEntry { get; set; }
        public string Code { get; set; }
        public string ActType { get; set; }
        public string ActDesc { get; set; }
        public string ActStatus { get; set; }
        public string ActMessage { get; set; }
        public string ActData { get; set; }
        public string ObjectID { get; set; }
        public string ReportID { get; set; }
        public Nullable<short> UserSign { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<short> UserSign2 { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<short> LogInstanc { get; set; }
        public string PeriodType { get; set; }
        public Nullable<int> PeriodNum { get; set; }
        public Nullable<short> Year { get; set; }
        public Nullable<System.DateTime> DateFrom { get; set; }
        public Nullable<System.DateTime> DateTo { get; set; }
        public Nullable<short> Submits { get; set; }
    }
}
