//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLVS.Dal.Company
{
    using System;
    using System.Collections.Generic;
    
    public partial class HEM6
    {
        public int empID { get; set; }
        public short line { get; set; }
        public Nullable<int> roleID { get; set; }
        public Nullable<int> LogInstanc { get; set; }
    }
}
