//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLVS.Dal.Company
{
    using System;
    using System.Collections.Generic;
    
    public partial class NNM1
    {
        public string ObjectCode { get; set; }
        public short Series { get; set; }
        public string SeriesName { get; set; }
        public Nullable<int> InitialNum { get; set; }
        public Nullable<int> NextNumber { get; set; }
        public Nullable<int> LastNum { get; set; }
        public string BeginStr { get; set; }
        public string EndStr { get; set; }
        public string Remark { get; set; }
        public Nullable<short> GroupCode { get; set; }
        public string Locked { get; set; }
        public string YearTransf { get; set; }
        public string Indicator { get; set; }
        public string Template { get; set; }
        public Nullable<int> NumSize { get; set; }
        public string FolioPref { get; set; }
        public Nullable<int> NextFolio { get; set; }
        public string DocSubType { get; set; }
        public Nullable<short> DefESeries { get; set; }
        public string IsDigSerie { get; set; }
        public string SeriesType { get; set; }
        public string IsManual { get; set; }
        public Nullable<int> BPLId { get; set; }
        public string IsForCncl { get; set; }
    }
}
