//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLVS.Dal.Company
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORST
    {
        public int AbsEntry { get; set; }
        public string RStageCode { get; set; }
        public string RStagDescr { get; set; }
        public string BarCodeVal { get; set; }
        public string EnforLocat { get; set; }
        public string EnforComme { get; set; }
        public string EnforOwner { get; set; }
    }
}
