//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLVS.Dal.Company
{
    using System;
    using System.Collections.Generic;
    
    public partial class OWHT
    {
        public string WTCode { get; set; }
        public string WTName { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public Nullable<System.DateTime> EffecDate { get; set; }
        public string Category { get; set; }
        public string BaseType { get; set; }
        public Nullable<decimal> PrctBsAmnt { get; set; }
        public string OffclCode { get; set; }
        public string Account { get; set; }
        public Nullable<decimal> MinTaxAmt { get; set; }
        public string IsPrgrss { get; set; }
        public string Type { get; set; }
        public string RoundType { get; set; }
        public Nullable<int> WTTypeId { get; set; }
        public string WTCurrency { get; set; }
        public Nullable<int> LogInstanc { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<short> UserSign { get; set; }
        public Nullable<int> Section { get; set; }
        public Nullable<decimal> Threshold { get; set; }
        public Nullable<decimal> Surcharge { get; set; }
        public string Concess { get; set; }
        public Nullable<int> Assessee { get; set; }
        public string ApTdsAcc { get; set; }
        public string ApSurAcc { get; set; }
        public string ApCessAcc { get; set; }
        public string ApHscAcc { get; set; }
        public string ArTdsAcc { get; set; }
        public string ArSurAcc { get; set; }
        public string ArCessAcc { get; set; }
        public string ArHscAcc { get; set; }
        public Nullable<int> Location { get; set; }
        public string ReturnType { get; set; }
        public Nullable<short> UserSign2 { get; set; }
        public string Inactive { get; set; }
        public Nullable<int> InCSTCode { get; set; }
        public Nullable<int> OutCSTCode { get; set; }
        public string CalBaseN { get; set; }
    }
}
