//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLVS.Dal.Company
{
    using System;
    using System.Collections.Generic;
    
    public partial class PDF6
    {
        public int DocNum { get; set; }
        public Nullable<int> InvoiceId { get; set; }
        public string WTCode { get; set; }
        public string PymMean { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<decimal> WTSum { get; set; }
        public Nullable<decimal> WTSumFC { get; set; }
        public Nullable<decimal> WTSumSC { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public Nullable<decimal> TaxbleAmnt { get; set; }
        public Nullable<decimal> TxblAmntFC { get; set; }
        public Nullable<decimal> TxblAmntSC { get; set; }
        public Nullable<decimal> PymAmount { get; set; }
        public Nullable<decimal> PymAmounF { get; set; }
        public Nullable<decimal> PymAmounS { get; set; }
        public int Line { get; set; }
        public Nullable<int> LogInstanc { get; set; }
        public string ObjType { get; set; }
        public Nullable<decimal> TdsBAmt { get; set; }
        public Nullable<decimal> TdsBAmtSC { get; set; }
        public Nullable<decimal> TdsBAmtFC { get; set; }
        public Nullable<decimal> SurBAmt { get; set; }
        public Nullable<decimal> SurBAmtSC { get; set; }
        public Nullable<decimal> SurBAmtFC { get; set; }
        public Nullable<decimal> CessBAmt { get; set; }
        public Nullable<decimal> CessBAmtSC { get; set; }
        public Nullable<decimal> CessBAmtFC { get; set; }
        public Nullable<decimal> HscBAmt { get; set; }
        public Nullable<decimal> HscBAmtSC { get; set; }
        public Nullable<decimal> HscBAmtFC { get; set; }
        public Nullable<decimal> TdsAmnt { get; set; }
        public Nullable<decimal> TdsAmntSC { get; set; }
        public Nullable<decimal> TdsAmntFC { get; set; }
        public Nullable<decimal> SurAmnt { get; set; }
        public Nullable<decimal> SurAmntSC { get; set; }
        public Nullable<decimal> SurAmntFC { get; set; }
        public Nullable<decimal> CessAmnt { get; set; }
        public Nullable<decimal> CessAmntSC { get; set; }
        public Nullable<decimal> CessAmntFC { get; set; }
        public Nullable<decimal> HscAmnt { get; set; }
        public Nullable<decimal> HscAmntSC { get; set; }
        public Nullable<decimal> HscAmntFC { get; set; }
    }
}
