//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLVS.Dal.Company
{
    using System;
    using System.Collections.Generic;
    
    public partial class POR5
    {
        public int AbsEntry { get; set; }
        public string WTCode { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public Nullable<decimal> TaxbleAmnt { get; set; }
        public Nullable<decimal> TxblAmntSC { get; set; }
        public Nullable<decimal> TxblAmntFC { get; set; }
        public Nullable<decimal> WTAmnt { get; set; }
        public Nullable<decimal> WTAmntSC { get; set; }
        public Nullable<decimal> WTAmntFC { get; set; }
        public Nullable<decimal> ApplAmnt { get; set; }
        public Nullable<decimal> ApplAmntSC { get; set; }
        public Nullable<decimal> ApplAmntFC { get; set; }
        public string Category { get; set; }
        public string Criteria { get; set; }
        public string Account { get; set; }
        public string Type { get; set; }
        public string RoundType { get; set; }
        public string BaseType { get; set; }
        public int BaseAbsEnt { get; set; }
        public Nullable<int> BaseLine { get; set; }
        public Nullable<int> BaseNum { get; set; }
        public int LineNum { get; set; }
        public Nullable<int> BaseRef { get; set; }
        public string Status { get; set; }
        public Nullable<int> TrgType { get; set; }
        public Nullable<int> TrgAbsEntr { get; set; }
        public Nullable<int> LogInstanc { get; set; }
        public string ObjType { get; set; }
        public int Doc1LineNo { get; set; }
        public string WtLineType { get; set; }
        public string TxblCurr { get; set; }
        public string DtblCurr { get; set; }
        public Nullable<decimal> DtblRate { get; set; }
        public Nullable<decimal> txblRate { get; set; }
        public Nullable<decimal> DtblAmount { get; set; }
        public string TdsAcc { get; set; }
        public string SurAcc { get; set; }
        public string CessAcc { get; set; }
        public string HscAcc { get; set; }
        public Nullable<decimal> TdsRate { get; set; }
        public Nullable<decimal> SurRate { get; set; }
        public Nullable<decimal> CessRate { get; set; }
        public Nullable<decimal> HscRate { get; set; }
        public Nullable<decimal> TdsBAmt { get; set; }
        public Nullable<decimal> TdsBAmtSC { get; set; }
        public Nullable<decimal> TdsBAmtFC { get; set; }
        public Nullable<decimal> SurBAmt { get; set; }
        public Nullable<decimal> SurBAmtSC { get; set; }
        public Nullable<decimal> SurBAmtFC { get; set; }
        public Nullable<decimal> CessBAmt { get; set; }
        public Nullable<decimal> CessBAmtSC { get; set; }
        public Nullable<decimal> CessBAmtFC { get; set; }
        public Nullable<decimal> HscBAmt { get; set; }
        public Nullable<decimal> HscBAmtSC { get; set; }
        public Nullable<decimal> HscBAmtFC { get; set; }
        public Nullable<decimal> TdsAmnt { get; set; }
        public Nullable<decimal> TdsAmntSC { get; set; }
        public Nullable<decimal> TdsAmntFC { get; set; }
        public Nullable<decimal> SurAmnt { get; set; }
        public Nullable<decimal> SurAmntSC { get; set; }
        public Nullable<decimal> SurAmntFC { get; set; }
        public Nullable<decimal> CessAmnt { get; set; }
        public Nullable<decimal> CessAmntSC { get; set; }
        public Nullable<decimal> CessAmntFC { get; set; }
        public Nullable<decimal> HscAmnt { get; set; }
        public Nullable<decimal> HscAmntSC { get; set; }
        public Nullable<decimal> HscAmntFC { get; set; }
        public Nullable<decimal> TdsAppl { get; set; }
        public Nullable<decimal> TdsApplSC { get; set; }
        public Nullable<decimal> TdsApplFC { get; set; }
        public Nullable<decimal> SurAppl { get; set; }
        public Nullable<decimal> SurApplSC { get; set; }
        public Nullable<decimal> SurApplFC { get; set; }
        public Nullable<decimal> CessAppl { get; set; }
        public Nullable<decimal> CessApplSC { get; set; }
        public Nullable<decimal> CessApplFC { get; set; }
        public Nullable<decimal> HscAppl { get; set; }
        public Nullable<decimal> HscApplSC { get; set; }
        public Nullable<decimal> HscApplFC { get; set; }
        public Nullable<int> BatchNum { get; set; }
        public string InCSTCode { get; set; }
        public string OutCSTCode { get; set; }
    }
}
