//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLVS.Dal.Company
{
    using System;
    using System.Collections.Generic;
    
    public partial class PWZ4
    {
        public int IdEntry { get; set; }
        public Nullable<int> PymNum { get; set; }
        public string CardCode { get; set; }
        public string CardName { get; set; }
        public string PymMeth { get; set; }
        public string GLAccCode { get; set; }
        public Nullable<decimal> PymAmount { get; set; }
        public Nullable<decimal> PymAmntFC { get; set; }
        public string ObjType { get; set; }
        public int RctId { get; set; }
        public string DocCurr { get; set; }
        public string BankAccou { get; set; }
        public string BnkDflt { get; set; }
        public string BankCountr { get; set; }
        public Nullable<int> BankActKey { get; set; }
        public string LineType { get; set; }
        public Nullable<int> ManualNum { get; set; }
        public string TBankCode { get; set; }
        public string TDflAccoun { get; set; }
        public string TBankCount { get; set; }
        public string TargetBran { get; set; }
        public Nullable<decimal> BcgPmnt { get; set; }
        public Nullable<decimal> BcgPmntFc { get; set; }
    }
}
