//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLVS.Dal.Company
{
    using System;
    using System.Collections.Generic;
    
    public partial class RCT8
    {
        public int DocNum { get; set; }
        public int LineNum { get; set; }
        public string InvType { get; set; }
        public Nullable<int> DocEntry { get; set; }
        public Nullable<int> DocLine { get; set; }
        public string ObjectType { get; set; }
        public Nullable<int> LogInstanc { get; set; }
    }
}
