//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLVS.Dal.Company
{
    using System;
    using System.Collections.Generic;
    
    public partial class TCD1
    {
        public int AbsId { get; set; }
        public int TcdId { get; set; }
        public Nullable<int> KeyFld_1 { get; set; }
        public Nullable<int> KeyFld_2 { get; set; }
        public Nullable<int> KeyFld_3 { get; set; }
        public int Priority { get; set; }
        public string Descr { get; set; }
        public Nullable<int> KeyFld_4 { get; set; }
    }
}
