//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLVS.Dal.Company
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRS1
    {
        public int AbsEntry { get; set; }
        public string ObjType { get; set; }
        public int LineID { get; set; }
        public string ApDocType { get; set; }
        public int ApDocEntry { get; set; }
        public int ApDocOrdNo { get; set; }
        public int RepostID { get; set; }
    }
}
