//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLVS.Dal.Company
{
    using System;
    using System.Collections.Generic;
    
    public partial class UGP1
    {
        public int UgpEntry { get; set; }
        public int UomEntry { get; set; }
        public Nullable<decimal> AltQty { get; set; }
        public Nullable<decimal> BaseQty { get; set; }
        public Nullable<int> LogInstanc { get; set; }
        public int LineNum { get; set; }
    }
}
