//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLVS.Dal.Company
{
    using System;
    using System.Collections.Generic;
    
    public partial class UWOR1
    {
        public int DocEntry { get; set; }
        public int LineNum { get; set; }
        public string ItemCode { get; set; }
        public Nullable<decimal> BaseQty { get; set; }
        public Nullable<decimal> PlannedQty { get; set; }
        public Nullable<decimal> IssuedQty { get; set; }
        public string IssueType { get; set; }
        public string wareHouse { get; set; }
        public Nullable<int> VisOrder { get; set; }
        public string WipActCode { get; set; }
        public Nullable<decimal> CompTotal { get; set; }
        public string OcrCode { get; set; }
        public string OcrCode2 { get; set; }
        public string OcrCode3 { get; set; }
        public string OcrCode4 { get; set; }
        public string OcrCode5 { get; set; }
        public Nullable<int> LocCode { get; set; }
        public Nullable<int> LogInstanc { get; set; }
        public Nullable<short> LoadFrBOM { get; set; }
        public string Project { get; set; }
        public Nullable<int> UomEntry { get; set; }
        public string UomCode { get; set; }
    }
}
