//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLVS.Dal.Company
{
    using System;
    using System.Collections.Generic;
    
    public partial class VRT2
    {
        public string TxInvRptNo { get; set; }
        public int GridRow { get; set; }
        public Nullable<int> BPLId { get; set; }
        public string BPCode { get; set; }
        public string BPName { get; set; }
        public Nullable<System.DateTime> DocDate { get; set; }
        public string ItemNo { get; set; }
        public string ItemDes { get; set; }
        public string TaxCode { get; set; }
        public Nullable<int> ItemQty { get; set; }
        public Nullable<decimal> ItemPrice { get; set; }
        public Nullable<decimal> BaseAmt { get; set; }
        public Nullable<decimal> TaxAmt { get; set; }
        public Nullable<int> LineType { get; set; }
        public Nullable<int> DocEntry { get; set; }
        public Nullable<int> DocType { get; set; }
        public Nullable<int> LineNum { get; set; }
        public string Currency { get; set; }
    }
}
