//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLVS.Dal.Company
{
    using System;
    using System.Collections.Generic;
    
    public partial class VRW2
    {
        public int AbsEntry { get; set; }
        public int TaxInvID { get; set; }
        public string VatGroup { get; set; }
        public string Selected { get; set; }
        public string LineStatus { get; set; }
        public string DebitAcc { get; set; }
        public Nullable<System.DateTime> DocDate { get; set; }
        public Nullable<decimal> VatAmount { get; set; }
        public Nullable<decimal> NetAmount { get; set; }
        public Nullable<int> JETransID { get; set; }
        public string Ref1 { get; set; }
        public string Ref2 { get; set; }
        public string Ref3 { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> LedgerID { get; set; }
    }
}
