//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLVS.Dal.Company
{
    using System;
    using System.Collections.Generic;
    
    public partial class WHT1
    {
        public string WTCode { get; set; }
        public Nullable<System.DateTime> EffecDate { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public Nullable<int> LogInstanc { get; set; }
        public Nullable<decimal> TdsRate { get; set; }
        public Nullable<decimal> SurRate { get; set; }
        public Nullable<decimal> CessRate { get; set; }
        public Nullable<decimal> HscRate { get; set; }
        public Nullable<short> PmntTerms { get; set; }
        public int LineNum { get; set; }
    }
}
