//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLVS.Dal.Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class EBCFG
    {
        public string Id { get; set; }
        public string LnscpId { get; set; }
        public string Company { get; set; }
        public Nullable<int> DefltRecvr { get; set; }
    }
}
