//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLVS.Dal.Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class EBUSR
    {
        public string B1Company { get; set; }
        public string B1User { get; set; }
        public byte[] Pwd { get; set; }
        public string Pwd2 { get; set; }
    }
}
