//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLVS.Dal.Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class EESUB
    {
        public string EventType { get; set; }
        public string Processor { get; set; }
        public string ReceiverId { get; set; }
        public string ReturnAddr { get; set; }
        public string SenderId { get; set; }
        public string FilterName { get; set; }
        public string FilterVal { get; set; }
    }
}
