//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLVS.Dal.Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMERR
    {
        public int ID { get; set; }
        public string QueueType { get; set; }
        public string IDInQueue { get; set; }
        public string ErrCode { get; set; }
        public string Severity { get; set; }
        public string ErrMessage { get; set; }
        public string Member { get; set; }
        public string ExcType { get; set; }
        public string ExcString { get; set; }
    }
}
