//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLVS.Dal.Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMMSG
    {
        public string ID { get; set; }
        public string Service { get; set; }
        public string Operation { get; set; }
        public string Sender { get; set; }
        public string Receiver { get; set; }
        public string InOut { get; set; }
        public string BOType { get; set; }
        public string BOID { get; set; }
        public string SboBoType { get; set; }
        public string SboBoID { get; set; }
    }
}
