//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLVS.Dal.Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class EPOPR
    {
        public int SrvId { get; set; }
        public string OprName { get; set; }
        public string SyncMode { get; set; }
        public string PrmMsgType { get; set; }
        public string PrcId { get; set; }
        public string RetMsgType { get; set; }
        public string ParamName { get; set; }
    }
}
