//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLVS.Dal.Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class EPSRV
    {
        public int Id { get; set; }
        public string PkgName { get; set; }
        public string SrvName { get; set; }
        public string Namespace { get; set; }
        public string SrvAddress { get; set; }
        public string InOut { get; set; }
    }
}
