//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLVS.Dal.Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class SARI
    {
        public int AddOnId { get; set; }
        public string NameSpace { get; set; }
        public string PName { get; set; }
        public string AName { get; set; }
        public string EName { get; set; }
        public string CData { get; set; }
        public string AddOnChk { get; set; }
        public string InstName { get; set; }
        public string InstChkSum { get; set; }
        public byte[] ABinary { get; set; }
        public Nullable<int> InstTime { get; set; }
        public string AddOnVer { get; set; }
        public string ForceFlag { get; set; }
        public string UnInstName { get; set; }
        public string UnInstChk { get; set; }
        public string UnInstPar { get; set; }
        public string InstIsUn { get; set; }
        public string AGroup { get; set; }
        public string IParams { get; set; }
        public Nullable<int> UnInstTime { get; set; }
        public string AutoAssign { get; set; }
        public string Visible { get; set; }
        public string SelfUpgrd { get; set; }
        public string InstSil { get; set; }
        public string UnInstSil { get; set; }
        public string UpgSil { get; set; }
        public byte[] InstParF { get; set; }
        public byte[] UnInstParF { get; set; }
        public byte[] UpgParF { get; set; }
        public string InstPFChk { get; set; }
        public string UnInstPFCh { get; set; }
        public string UpgPFChk { get; set; }
        public string UpgName { get; set; }
        public Nullable<int> UpgTime { get; set; }
        public string UpgParams { get; set; }
        public byte[] AUpgrader { get; set; }
        public string UpgChkSum { get; set; }
        public byte[] ABinary64 { get; set; }
        public string IsAdd64 { get; set; }
        public string AddPlat { get; set; }
    }
}
