//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLVS.Dal.Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCLC
    {
        public int LangCode { get; set; }
        public Nullable<int> BaseID { get; set; }
        public Nullable<int> HotKeyID { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
        public byte[] File { get; set; }
        public string FileName { get; set; }
        public Nullable<int> UpdTime { get; set; }
        public string Version { get; set; }
        public string PatchLevel { get; set; }
    }
}
