//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLVS.Dal.Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class SDRC
    {
        public string ObjectId { get; set; }
        public string DescStr { get; set; }
        public Nullable<short> VisOrder { get; set; }
        public string PartOf { get; set; }
    }
}
