//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLVS.Dal.Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class SDRQ
    {
        public string ObjTo { get; set; }
        public string ObjFrom { get; set; }
        public string JoinStr { get; set; }
        public string FilterStr { get; set; }
        public int ServerType { get; set; }
    }
}
