//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLVS.Dal.Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEULA
    {
        public string Locale { get; set; }
        public string EULAType { get; set; }
        public byte[] EULADoc { get; set; }
        public string Format { get; set; }
        public string CheckSum { get; set; }
    }
}
