//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLVS.Dal.Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEVT
    {
        public int SequenceID { get; set; }
        public string SourceDB { get; set; }
        public string Timestamp { get; set; }
        public string Status { get; set; }
        public Nullable<int> Retry { get; set; }
        public string ObjectType { get; set; }
        public string TransType { get; set; }
        public Nullable<int> FieldsInKe { get; set; }
        public string FieldNames { get; set; }
        public string FieldValue { get; set; }
        public string UserID { get; set; }
        public string USER_CODE { get; set; }
    }
}
