//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLVS.Dal.Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEWAD
    {
        public int AbsEntry { get; set; }
        public string DbName { get; set; }
        public Nullable<int> AddonId { get; set; }
        public string AddonName { get; set; }
        public string AddonVer { get; set; }
        public string NameSpace { get; set; }
        public string PartName { get; set; }
    }
}
