//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLVS.Dal.Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEWC
    {
        public string CompDbNam { get; set; }
        public string SmpTableId { get; set; }
        public string COAtemplat { get; set; }
        public string LocalCurr { get; set; }
        public string SystemCurr { get; set; }
        public string UseSegAcc { get; set; }
        public string StkValuat { get; set; }
        public string PricSysPWh { get; set; }
        public string AllowRelSt { get; set; }
        public string CostPrcLst { get; set; }
        public string GrossBySal { get; set; }
        public string BlkNegQuan { get; set; }
        public string RoundMeth { get; set; }
        public string RoundVAT { get; set; }
        public string EnblExpns { get; set; }
        public string DirectRate { get; set; }
        public Nullable<int> SumDec { get; set; }
        public Nullable<int> PriceDec { get; set; }
        public Nullable<int> RateDec { get; set; }
        public Nullable<int> QtyDec { get; set; }
        public Nullable<int> PercentDec { get; set; }
        public Nullable<int> MeasureDec { get; set; }
        public string DecSep { get; set; }
        public string DpmSalAct { get; set; }
        public string DfltIncom { get; set; }
        public string ForgnIncm { get; set; }
        public string ECIncome { get; set; }
        public string SHandleWT { get; set; }
        public string SDfltWT { get; set; }
        public string NINum { get; set; }
        public Nullable<System.DateTime> ExpireDate { get; set; }
        public string CrtfcateNO { get; set; }
        public string SaleVatOff { get; set; }
        public string DfltExpn { get; set; }
        public string ForgnExpn { get; set; }
        public string ECExepnses { get; set; }
        public string DpmPurAct { get; set; }
        public string ExpVarAct { get; set; }
        public string PHandleWT { get; set; }
        public string PDfltWT { get; set; }
        public string PurcVatOff { get; set; }
        public string ComissAct { get; set; }
    }
}
