//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLVS.Dal.Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEWDV
    {
        public string CompDbNam { get; set; }
        public string SmpTableId { get; set; }
        public string EwaSentDat { get; set; }
        public string CustNumber { get; set; }
        public string DocPeriod { get; set; }
        public Nullable<int> SalesOrdrs { get; set; }
        public Nullable<int> SalDlvDocs { get; set; }
        public Nullable<int> SalesInvs { get; set; }
        public Nullable<int> PurcOrders { get; set; }
        public Nullable<int> GoodRecpts { get; set; }
        public Nullable<int> PurchAPInv { get; set; }
        public Nullable<int> ServicCall { get; set; }
        public Nullable<int> MaterBills { get; set; }
        public Nullable<int> WorkOrders { get; set; }
        public Nullable<int> SalesOppor { get; set; }
        public Nullable<int> ItmMasterD { get; set; }
        public Nullable<int> CustBPMasD { get; set; }
        public Nullable<int> SuppBPMasD { get; set; }
        public Nullable<int> SalOrdMinR { get; set; }
        public Nullable<int> SlDlvrMinR { get; set; }
        public Nullable<int> SlsInvMinR { get; set; }
        public Nullable<int> PrcOrdMinR { get; set; }
        public Nullable<int> GodRcpMinR { get; set; }
        public Nullable<int> WrkOrdMinR { get; set; }
        public Nullable<int> QuotMinR { get; set; }
        public Nullable<int> RetMinR { get; set; }
        public Nullable<int> DownMinR { get; set; }
        public Nullable<int> ARCrdMinR { get; set; }
        public Nullable<int> GodRecMinR { get; set; }
        public Nullable<int> APRetMinR { get; set; }
        public Nullable<int> APDwnMinR { get; set; }
        public Nullable<int> APInvMinR { get; set; }
        public Nullable<int> APCrdMinR { get; set; }
        public Nullable<int> SalOrdMaxR { get; set; }
        public Nullable<int> SlDlvrMaxR { get; set; }
        public Nullable<int> SlsInvMaxR { get; set; }
        public Nullable<int> PrcOrdMaxR { get; set; }
        public Nullable<int> GodRcpMaxR { get; set; }
        public Nullable<int> WrkOrdMaxR { get; set; }
        public Nullable<int> QuotMaxR { get; set; }
        public Nullable<int> RetMaxR { get; set; }
        public Nullable<int> DownMaxR { get; set; }
        public Nullable<int> ARCrdMaxR { get; set; }
        public Nullable<int> GodRecMaxR { get; set; }
        public Nullable<int> APRetMaxR { get; set; }
        public Nullable<int> APDwnMaxR { get; set; }
        public Nullable<int> APInvMaxR { get; set; }
        public Nullable<int> APCrdMaxR { get; set; }
        public Nullable<int> NoPickLst { get; set; }
        public Nullable<int> MaxLnPkLst { get; set; }
        public Nullable<int> MinLnPkLst { get; set; }
        public Nullable<int> MaxChldBm { get; set; }
        public Nullable<int> NoProdOrd { get; set; }
        public Nullable<int> NoSrlNum { get; set; }
        public Nullable<int> NoBatchNum { get; set; }
        public Nullable<int> StockTras { get; set; }
        public Nullable<int> MaxRStTrs { get; set; }
        public Nullable<int> MinRStTrs { get; set; }
        public Nullable<int> NoPriceLst { get; set; }
    }
}
