//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLVS.Dal.Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEWDB
    {
        public string AbsEntry { get; set; }
        public string SmpTableId { get; set; }
        public string CollectDat { get; set; }
        public string CompDbName { get; set; }
        public string DbPath { get; set; }
        public string PrevDbSize { get; set; }
        public string DbSize { get; set; }
        public string TranLogSiz { get; set; }
        public string TranLogPat { get; set; }
        public string TotalDbSiz { get; set; }
        public string FreDskSpac { get; set; }
        public string MaxDbSize { get; set; }
        public string MaxLogSize { get; set; }
    }
}
