//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLVS.Dal.Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEWHW
    {
        public string MachineNam { get; set; }
        public string CompDbNam { get; set; }
        public string SmpTableId { get; set; }
        public string EwaSentDat { get; set; }
        public string CustNumber { get; set; }
        public string OsType { get; set; }
        public string OsVersion { get; set; }
        public string VendorIden { get; set; }
        public string CpuType { get; set; }
        public Nullable<int> NumOfCPUs { get; set; }
        public Nullable<int> PhysMemory { get; set; }
        public string ServerFlag { get; set; }
        public string TotDskSpac { get; set; }
        public string FreDskSpac { get; set; }
        public string UseDskSpac { get; set; }
    }
}
