//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLVS.Dal.Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEWIC
    {
        public string CompanyNam { get; set; }
        public string SmpTableId { get; set; }
        public string EwaSentDat { get; set; }
        public string EwaSentTim { get; set; }
        public string CustNumber { get; set; }
        public string CustName { get; set; }
        public string CustConPer { get; set; }
        public string CustEmail { get; set; }
        public string PartnerNam { get; set; }
        public string PartConPer { get; set; }
        public string PartEmail { get; set; }
        public string PartEmail2 { get; set; }
        public string CompDbName { get; set; }
        public string CompDbVer { get; set; }
        public string SentUser { get; set; }
        public string B1Version { get; set; }
        public string B1Suppack { get; set; }
        public string B1Patch { get; set; }
        public string UiApiVer { get; set; }
        public string InstallNum { get; set; }
        public string SystemNum { get; set; }
        public string LicenseNum { get; set; }
        public string SystemStat { get; set; }
        public string DbType { get; set; }
        public string DbVersion { get; set; }
        public string CommLogPat { get; set; }
        public Nullable<int> CommLogSiz { get; set; }
        public string CommRecovM { get; set; }
        public string AOFramewor { get; set; }
        public string AODtw { get; set; }
        public string AOSupTools { get; set; }
        public string AODateV { get; set; }
        public string AOAld { get; set; }
        public string AOBcSets { get; set; }
        public string AOElster { get; set; }
        public string AOFixAsset { get; set; }
        public string AOIntrStat { get; set; }
        public string AOOutlookI { get; set; }
        public string AOPayEngin { get; set; }
        public string AOStampIt { get; set; }
        public string CompRecovM { get; set; }
    }
}
