//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLVS.Dal.Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEWST
    {
        public string Code { get; set; }
        public string Name { get; set; }
        public string U_SentDate { get; set; }
        public string U_SentTime { get; set; }
        public string U_UserID { get; set; }
        public string U_RCode { get; set; }
        public string U_RInfo { get; set; }
        public string U_AutoSent { get; set; }
    }
}
