//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLVS.Dal.Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEWSN
    {
        public string MachineNam { get; set; }
        public string CompDbNam { get; set; }
        public Nullable<int> CollecStat { get; set; }
        public string SentUser { get; set; }
        public string CompleDate { get; set; }
    }
}
