//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLVS.Dal.Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEWSY
    {
        public string S_USER { get; set; }
        public string SmpSendAdd { get; set; }
        public string SmpInboAdd { get; set; }
        public string CollecData { get; set; }
        public string FindSolAdd { get; set; }
        public string FeedOptAdd { get; set; }
    }
}
