//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLVS.Dal.Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEWUA
    {
        public string CompDbNam { get; set; }
        public Nullable<int> NoUdfDb { get; set; }
        public Nullable<int> NoTblUdf { get; set; }
        public Nullable<int> NoAutoFMS { get; set; }
        public Nullable<int> NoRegFMS { get; set; }
        public Nullable<int> NoCustTmpl { get; set; }
    }
}
