//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLVS.Dal.Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEWU3
    {
        public int AbsEntry { get; set; }
        public string CompanyNam { get; set; }
        public string SmpTableId { get; set; }
        public string EwaSentDat { get; set; }
        public string CustNumber { get; set; }
        public string CompDbName { get; set; }
        public string EwaUserCod { get; set; }
        public string EwaUserNam { get; set; }
        public string EwaUserSup { get; set; }
    }
}
