//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLVS.Dal.Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class SFDK
    {
        public int ID { get; set; }
        public string WindowID { get; set; }
        public string DBName { get; set; }
        public Nullable<int> UserSign { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<short> Time { get; set; }
        public string Version { get; set; }
        public string LOC { get; set; }
        public string UILang { get; set; }
        public Nullable<short> Feedback { get; set; }
        public string GUID { get; set; }
        public string StrLID { get; set; }
        public string StrIID { get; set; }
        public string MsgText { get; set; }
    }
}
