//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLVS.Dal.Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class SHQR
    {
        public int Version { get; set; }
        public string TableId { get; set; }
        public short Instance { get; set; }
        public string DoBefore { get; set; }
        public string QurString { get; set; }
        public int ServerType { get; set; }
    }
}
