//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLVS.Dal.Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class SINF
    {
        public int Version { get; set; }
        public string Flags { get; set; }
        public byte[] UpgCab { get; set; }
        public Nullable<System.DateTime> AppDate { get; set; }
        public string ClusterID { get; set; }
        public Nullable<short> AppTime { get; set; }
        public string ShrPath { get; set; }
        public Nullable<short> Algo { get; set; }
        public string PatchLevel { get; set; }
        public string BuildDesc { get; set; }
    }
}
