//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLVS.Dal.Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class SLOGR
    {
        public int LogKey { get; set; }
        public string CompName { get; set; }
        public string LoginName { get; set; }
        public Nullable<int> ProcessID { get; set; }
        public Nullable<System.DateTime> LogDate { get; set; }
        public byte[] LogFile { get; set; }
        public Nullable<int> Archive { get; set; }
    }
}
