//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLVS.Dal.Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class SLOG
    {
        public string LogConfig { get; set; }
        public string UseDBConf { get; set; }
        public string ActLog { get; set; }
        public Nullable<System.DateTime> ModDate { get; set; }
        public string LogDefConf { get; set; }
        public string ReposConf { get; set; }
        public int AbsKey { get; set; }
        public Nullable<short> ModTime { get; set; }
    }
}
