//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLVS.Dal.Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class SLSC
    {
        public string LocCode { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }
        public byte[] DataCab { get; set; }
        public string System { get; set; }
    }
}
