//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLVS.Dal.Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class SRGC
    {
        public string dbName { get; set; }
        public string cmpName { get; set; }
        public string versStr { get; set; }
        public string dbUser { get; set; }
        public string LOC { get; set; }
    }
}
