//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLVS.Dal.Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class SWEI
    {
        public string EngineAddr { get; set; }
        public string EngineVer { get; set; }
        public Nullable<int> HashCode { get; set; }
        public string StartTime { get; set; }
        public string LastUpdate { get; set; }
        public string NextUpdate { get; set; }
        public string EngCmpnys { get; set; }
    }
}
