//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLVS.Dal.Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class SWPD
    {
        public int ProcDefID { get; set; }
        public Nullable<int> DeploymtID { get; set; }
        public Nullable<int> ResourceID { get; set; }
        public string Key { get; set; }
        public string Name { get; set; }
        public string Desc { get; set; }
        public string Category { get; set; }
        public string Version { get; set; }
        public string ProcType { get; set; }
        public string Status { get; set; }
        public string StartType { get; set; }
    }
}
