//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLVS.Dal.Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class SWR
    {
        public int ResourceID { get; set; }
        public string Name { get; set; }
        public string Version { get; set; }
        public Nullable<int> DeploymtID { get; set; }
        public byte[] Bytes { get; set; }
    }
}
