//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLVS.Dal.Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class SXRCO
    {
        public int ContextId { get; set; }
        public string B1User { get; set; }
        public string Password { get; set; }
        public Nullable<int> Language { get; set; }
        public Nullable<int> Applicatio { get; set; }
        public Nullable<System.DateTime> LogonDate { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public string Constrain { get; set; }
        public string DB { get; set; }
        public Nullable<int> ForceCust { get; set; }
        public string Roles { get; set; }
        public string InvalidTer { get; set; }
    }
}
