//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLVS.Dal.Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class SXRCD
    {
        public int classid { get; set; }
        public string name { get; set; }
        public string descriptio { get; set; }
        public Nullable<System.DateTime> created { get; set; }
        public Nullable<System.DateTime> lastmodifi { get; set; }
    }
}
