//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLVS.Dal.Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class SXRDF
    {
        public int DimFilterI { get; set; }
        public string RoleId { get; set; }
        public string DimId { get; set; }
        public string ModuleId { get; set; }
        public Nullable<int> AccessType { get; set; }
        public string ReadInclud { get; set; }
    }
}
