//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLVS.Dal.Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class SXREL
    {
        public int EventId { get; set; }
        public Nullable<int> Type { get; set; }
        public string Text { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    }
}
