//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLVS.Dal.Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class SXROA
    {
        public int ObjectAcce { get; set; }
        public string RoleId { get; set; }
        public string ObjId { get; set; }
        public string SubId { get; set; }
        public Nullable<int> AccessLeve { get; set; }
    }
}
