//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLVS.Dal.Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class SXRPR
    {
        public int propid { get; set; }
        public Nullable<int> objid { get; set; }
        public Nullable<int> propdefid { get; set; }
        public Nullable<int> ivalue { get; set; }
        public Nullable<decimal> fvalue { get; set; }
        public string cvalue { get; set; }
    }
}
