//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLVS.Dal.Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class SXRPD
    {
        public int propdefid { get; set; }
        public Nullable<int> classid { get; set; }
        public Nullable<int> seqno { get; set; }
        public string name { get; set; }
        public string category { get; set; }
        public string descriptio { get; set; }
        public Nullable<int> type { get; set; }
        public Nullable<int> minoccurs { get; set; }
        public Nullable<int> maxoccurs { get; set; }
        public Nullable<int> classrefid { get; set; }
        public Nullable<int> enumid { get; set; }
    }
}
