//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLVS.Dal.Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class SXRSS
    {
        public int SecuritySe { get; set; }
        public string AppId { get; set; }
        public string DatabaseId { get; set; }
        public string ModuleId { get; set; }
        public string Label { get; set; }
        public string Value { get; set; }
    }
}
