//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLVS.Dal.Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSCD
    {
        public string SrvcName { get; set; }
        public string SchedType { get; set; }
        public Nullable<System.DateTime> SchedDate { get; set; }
        public string SchedDay { get; set; }
        public Nullable<int> Interval { get; set; }
        public System.DateTime LastExDate { get; set; }
        public string AutoStart { get; set; }
    }
}
